### ISSUE TITLE
Wrong links for Terms & Conditions

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet-fork#15]
**Describe the bug**
When I start XT Wallet (Firefox) i need ot accept Terms & Conditions. 
They are linked to Tezos instead it should to Signum

![grafik](https://user-images.githubusercontent.com/39116221/153703800-a12f7fcf-0e43-44cc-92b0-4d4523aa3daf.png)

**Browser (please complete the following information):**
Firefox

**Comment by ohager** [comment]
ooops

**Comment by shefass** [comment]
If you @frankTheTank72  give correct links, I can change them. Them are here: 
https://github.com/signum-network/signum-xt-wallet/blob/17a54a1815c111d86466a13235083cc517001ab9/src/app/templates/NewWallet.tsx#L211
https://github.com/signum-network/signum-xt-wallet/blob/17a54a1815c111d86466a13235083cc517001ab9/src/app/templates/NewWallet.tsx#L223

**Comment by shefass** [comment]
#24 
Fixed

**Comment by ohager** [comment]
Fixed in #24
