### ISSUE TITLE
Load more button is shown ; but only 1 tx

### ISSUE THREAD

**Issue by frankTheTank72** [signum-network/signum-xt-wallet-fork#16]
**Describe the bug**
My wallet has one transaction - but still the button "load more" os shown

**Screenshots**
![grafik](https://user-images.githubusercontent.com/39116221/153703991-8ac768cc-5ddd-4667-a0a1-59ef35a9929b.png)

**Browser (please complete the following information):**
Firefox

**Comment by frankTheTank72** [comment]
Button went away after thr tx was not longer pending

**Comment by shefass** [comment]
fix #25

**Comment by ohager** [comment]
This is not a bug

**Comment by ohager** [comment]
Fixed in #25
