### ISSUE TITLE
too small window to perform reset the wallet

### ISSUE THREAD

**Issue by alicks** [signum-network/signum-xt-wallet-fork#18]
I was unable to reset wallet, as window (see screenshot) looks small and not expandable.
But if operate XT wallet in full screen mode - it ok.

**To Reproduce**
Press Icon (operate in small window, not in full screen) -> Got to SETTINGS -> GENERAL -> Reset Extension

**Expected behavior**
Confimation for Reseting should be visible.

**Screenshots**

**Browser (please complete the following information):**
 - Debian 11
 - FireFox EXR latest
 - 91.5.0esr (64-bit)

![image](https://user-images.githubusercontent.com/10243140/153712634-f742ec09-9fcb-4fbb-8f48-bdcdfa95963f.png)

**Comment by ohager** [comment]
thanks. Do you know that you can "pop-out" the wallet to full screen? Use the "Maximize View" option in the menu

**Comment by alicks** [comment]
Yes. With Maximize veiw - everything is visible.. But it took time to understand it, as by default as small view is opened. Basically, this more convinient way to operate for me. Perhaps, not a bug, but small inconvenience in operation.

**Comment by ohager** [comment]
btw: The options page is a standard of each extension and can be reached using right click on the extionsions icon.... but I agree that the reset thing should open the options in full page mode automatically

**Comment by shefass** [comment]
I can't reproduce it. For Ubuntu 20.04.3 LTS and latest FireFox all looks good on a small window.

**Comment by shefass** [comment]
Now I see it, reproduced.

**Comment by ohager** [comment]
Apparently, address somehow in #40 --- Need to test it, if it is sufficient. Then, I eventually close this issue
