### ISSUE TITLE
Visual bug. Random . at Send dialog.

### ISSUE THREAD

**Issue by shefass** [signum-network/signum-xt-wallet-fork#22]
**Describe the bug**
Random dot "." on top of "Recipient" word at Send dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/39196313/153744606-304c75de-0e50-4044-ad0b-fac96ffc887b.png)

**Browser (please complete the following information):**
 - OS: Ubuntu
 - Browser FireFox

**Comment by ohager** [comment]
This is no bug, but an enhancement!

**Comment by ohager** [comment]
Fixed in #23
