### ISSUE TITLE
Add the option to change the name of the account

### ISSUE THREAD

**Issue by rever273** [signum-network/signum-xt-wallet-fork#30]
In Full size version we can change account name, but we can't do it in separate window.

![image](https://user-images.githubusercontent.com/77928665/153844624-42c5ecfc-a018-4f00-9504-154c87ffef4d.png)

 - Version 1.0.1
 
 Discord: Roman273#0506

**Comment by ohager** [comment]
Available in fullscreen mode. Closing.
