### ISSUE TITLE
Node europe3.testnet.signum.network is labeled as unknown (trailing slashes should be ignored)

### ISSUE THREAD

**Issue by map1336** [signum-network/signum-xt-wallet-fork#37]
**Describe the bug**
When i'm trying to connect my wallet to the DApp in:
https://blockplay-website-develop-8xwcupy5d-shefass.vercel.app/
The dialog says that ``europe3.testnet.signum.network`` is ``UNKNOWN NETWORK``

**Steps to reproduce the behavior:**
1. Go to https://blockplay-website-develop-8xwcupy5d-shefass.vercel.app
2. Click on Connect to Signum XT Wallet
3. See error

**Expected behavior**
As it is an official test-net node which i saw on test-net explorer, it should not be labeled as Unknown

**Screenshots**
![image](https://user-images.githubusercontent.com/35440957/154174828-abae4bb1-0c1b-46e0-8c59-f9bfb9dedab8.png)
![image](https://user-images.githubusercontent.com/35440957/154175467-1b12e1ac-b9dc-4f21-b36b-c06cde8df0dc.png)

**Browser (please complete the following information):**
 - OS: Windows 10
 - Browser: Brave
 - Version 1.0.1 (Development mode)

**Comment by ohager** [comment]
Does it work, or is the functionality broken? If not broken, please mark this as an enhancement/improvement

**Comment by map1336** [comment]
It works, is just the node labeled as unknown

**Comment by shefass** [comment]
@ohager please close this

**Comment by ohager** [comment]
Is it fixed though?

**Comment by shefass** [comment]
yes. Function which checks looks for https://europe3.testnet.signum.network
, but it is written https://europe3.testnet.signum.network/, so it labels
it as unknown

2022-02-18, pn, 21:34 ohager ***@***.***> rašė:

**Comment by ohager** [comment]
ok... but let's keep it open. I will improve the find network function, such that trailing slashes are no issue anymore

**Comment by ohager** [comment]
Will close as the entire network selection feature will change significantly - I'll keep you updated
