### ISSUE TITLE
Odd wording on delete app

### ISSUE THREAD

**Issue by rogerwim** [signum-network/signum-xt-wallet-fork#46]
**Describe the bug**
reset permissions message is oddly worded
![image](https://user-images.githubusercontent.com/33426007/154505317-921d0b0d-be46-4c44-9bf1-d538f7246bdb.png)

**To Reproduce**
go to settings -> Dapps and click the X on a app

**Comment by ohager** [comment]
lol - looks really weird

**Comment by rogerwim** [comment]
#47 will fix this

**Comment by ohager** [comment]
closed as fixed in #47
