### ISSUE TITLE
Button Clean in importing "Watch-only" account does not work

### ISSUE THREAD

**Issue by map1336** [signum-network/signum-xt-wallet-fork#5]
**Describe the bug**
Everytime i try to click the icon button "Clean" the input does not get cleaned, nothing happens

**To Reproduce**
1. Import account
2. Select "Watching" mode
3. Put in address field "1673574549656521245"
4. Click on "X" icon

**Expected behavior**
The input's value must be emptied

**Screenshots**
![image](https://user-images.githubusercontent.com/35440957/153254761-0f343cc1-17e1-4bf1-87bb-5b76351446b7.png)

**Browser (please complete the following information):**
- OS: Windows 10
- Browser Version 98.0.4758.82
- Version 1.0.0 (Development mode)

**Comment by ohager** [comment]
fixed
