### ISSUE TITLE
"Watch-only" accounts should be hidden in list of "Confirm connection"

### ISSUE THREAD

**Issue by map1336** [signum-network/signum-xt-wallet-fork#6]
**Is your feature request related to a problem? Please describe.**
Once i get in development mode of NFT portal, i tried to connect the portal with a "Watch-only" account, and then i get the following feedback: `Error: Failed to reveal public key`

**Screenshots**
![image](https://user-images.githubusercontent.com/35440957/153258999-954df049-f78f-4eee-aa2d-39820ee81f3c.png)

**After i click on Connect**
![image](https://user-images.githubusercontent.com/35440957/153258624-b762a74a-ceec-42eb-b1c1-c719c416c536.png)

**Describe the solution you'd like**
When "Confirming a connection" try to delete "Watch-only" accounts from the list because obviously the portal requires "full" accounts

**Describe alternatives you've considered**
Maybe different DApps may interact normally with a "Wach-only" account but in this case for the NFT portal, tbh i think is not necessary to show them...

**Comment by ohager** [comment]
fixed
