### ISSUE TITLE
Some text are not translated to its corresponding locale

### ISSUE THREAD

**Issue by map1336** [signum-network/signum-xt-wallet-fork#8]
**Describe the bug**
Some text are not properly translated to its proper language, even tough i'm aware that i did typed the proper word in the spanish locales file

**Steps to reproduce the behavior:**
1. Update spanish locale file
2. See error

**Expected behavior**
The text should be translated to its proper language.

**Additional context**
TBH, is a low-priority issue compared to others, this is just small typos but is a + to share them!

**Browser:**
- OS: Windows 10
- Browser Version 98.0.4758.82
- Version 1.0.0 (Development mode)

**Multiple Screenshots**

1- **Black tooltip should say `Desactivado para la cuenta de sólo lectura`**
![bug1](https://user-images.githubusercontent.com/35440957/153268994-8ae6f067-b9a4-4f35-b854-5e1d50e36414.png)

2- **On delete account page and the log-in page, when i type the wrong password, 
        i could not find the locale of `Invalid password` in the json file**
![bug2](https://user-images.githubusercontent.com/35440957/153269583-f40bf6f3-ebd7-4bcb-938b-be08c1a28707.png)
![Bug4](https://user-images.githubusercontent.com/35440957/153270636-aa1938aa-bc5d-420c-8401-66df7dd72966.png)

3- **On onboarding page, i could not find the locale of `step` in the json file**
![Bug3](https://user-images.githubusercontent.com/35440957/153270267-d22f7ab8-34ad-4b19-8e35-4d10badf426d.png)

4- **On Node selection page, i could not find the locale of `Add network node` in the json file**
![bug5](https://user-images.githubusercontent.com/35440957/153270844-9782c38f-2988-4bc1-909e-6b23e096fc87.png)

5- **When i was trying to connect the NFT portal with a "Watch-only" account. 
I could not find the locale of `Failed to reveal public key` in the json file**
![Importing only watch account](https://user-images.githubusercontent.com/35440957/153271260-82cc4eb0-d274-4a21-8008-f847dcc1514a.png)

**Comment by ohager** [comment]
Error Messages come from down below.... rest is fixed
